### ISSUE TITLE
CheckoutSession::create ?

### ISSUE THREAD

**Issue by rrrodzilla** [arlyon/stripe-rs#24]
I can see the CheckoutSession struct but it doesn't appear to have the ability to create one.  Am I missing it somewhere or does it just not exist?  Thx.

**Comment by arlyon** [comment]
Hi! The way this library works is that we generate rust types for as many endpoints as possible, then implement the actual logic in the `ext` file. So you're right, we're missing the impl for `CheckoutSession`, but I am very open to PRs given that the original project seems unmaintained. I've marked this as a feature request.

**Comment by arlyon** [comment]
I also added a short paragraph explaining the general 'setup' to contributing.md. I think it should be fairly easy to implement, but if you'd like some pointers I'm happy to help!

**Comment by arlyon** [comment]
@rrrodzilla some more context: https://github.com/wyyerd/stripe-rs/issues/85

**Comment by arlyon** [comment]
@rrrodzilla I handled this while working towards #32, please target master and give it a spin

**Comment by rrrodzilla** [comment]
Hey Alexander,

Sorry about the long delay, I had to work on other things.  This seems to be working great.  The struct names are pretty verbose but nothing some aliases during usage.  Either way it works just fine and produces a valid checkout session.  Thanks for that!  If I use it for implementation I'll clean up some example code to include in the docs.

-Roland
